requests: support a list of requests and no-session support
westerndigitalcorporation/spdm-utils pull request #101
Opened 2024-08-07 02:16 UTC by twilfredo

2024-08-07 02:17 UTC, twilfredo commented
This is a modified approach from https://github.com/westerndigitalcorporation/spdm-utils/pull/97 to address the review comments.

2024-08-07 02:19 UTC, twilfredo commented on src/main.rs
> +}
Any thoughts on if this could be made better? Currently just manually parsing...

2024-08-07 03:43 UTC, alistair23 requested changes
Looks great! Let's add some unit tests though

2024-08-07 03:43 UTC, alistair23 commented on src/main.rs
> +        warn!("Input {s}");
`info!` instead of `warn!`?

2024-08-07 03:43 UTC, alistair23 commented on src/main.rs
> +    no_session: bool,
Default true maybe just to be explicit?

2024-08-07 03:43 UTC, alistair23 commented on src/main.rs
> +}
Not that I know of. I didn't see anything obvious in clap.

I think we should add some unit tests though that call `parse_request_codes()` with a range of tests that are run as part of `cargo test`

2024-08-07 04:17 UTC, twilfredo commented on src/main.rs
> +}
I was thinking that too, I'll add some

2024-08-07 04:17 UTC, twilfredo commented on src/main.rs
> +        warn!("Input {s}");
that's actually left over from testing, I'll remove it!

2024-08-07 04:18 UTC, twilfredo commented on src/main.rs
> +    no_session: bool,
good point!

2024-08-07 10:29 UTC, twilfredo commented
> Looks great! Let's add some unit tests though

Added a two tests cases that cover a range of positive and negative tests. Let me know if the coverage is ok

2024-08-08 02:53 UTC, alistair23 approved these changes

2024-08-08 02:53 UTC, merged