spdm_transport: generic: refactor IO buffers
westerndigitalcorporation/spdm-utils pull request #120
Opened 2024-10-31 05:19 UTC by twilfredo

This allows us to remove alot of repeated code for buffer `set/get`. This approach uses a heap allocated vector and just passes a reference to `libspdm` when required.

The assocaited memory shall be explicitly freed
by taking ownership when the buffer are no longer required. Which can be done by calling `libspdm_drop_io_buffers()`.

2024-10-31 05:21 UTC, twilfredo commented
to go in after https://github.com/westerndigitalcorporation/spdm-utils/pull/119

2024-11-08 00:19 UTC, alistair23 requested changes

2024-11-08 00:19 UTC, alistair23 commented on src/usb_i2c.rs
> +        io_buffers::libspdm_setup_io_buffers(context, SEND_RECEIVE_BUFFER_LEN, LIBSPDM_BUFFER_LEN)?;
Shouldn't these both be SEND_RECEIVE_BUFFER_LEN?

2024-11-08 00:19 UTC, alistair23 commented on src/io_buffers.rs
> +/// Panics if the SEND_BUFFER is not available
We can remove this comment now

2024-11-08 00:27 UTC, twilfredo commented on src/usb_i2c.rs
> +        io_buffers::libspdm_setup_io_buffers(context, SEND_RECEIVE_BUFFER_LEN, LIBSPDM_BUFFER_LEN)?;
In this particular case no, _iirc_ the reason was that we have the MCTP header accounted for in the `SEND_RECEIVE_BUFFER_LEN` and `LIBSPDM_BUFFER_LEN` is the actual SPDM message. This should be consistent with existing functionality:

https://github.com/westerndigitalcorporation/spdm-utils/blob/1bf3c1b21adbc03231cd6f835715c1a31915a02e/src/usb_i2c.rs#L444

```
        libspdm_register_device_buffer_func(
            context,
            LIBSPDM_BUFFER_LEN as u32,
            LIBSPDM_BUFFER_LEN as u32,
            Some(usb_i2c_acquire_sender_buffer),
            Some(usb_i2c_release_sender_buffer),
            Some(usb_i2c_acquire_receiver_buffer),
            Some(usb_i2c_release_receiver_buffer),
        );
```

Hence why I also had to make `libspdm_setup_io_buffers()` take two length arguments. So the upper level can determine which buffer lengths get set into `libspdm`, See https://github.com/westerndigitalcorporation/spdm-utils/blob/44b76c7c7d294f23a1f2d93d5089cbac6c2fbde9/src/io_buffers.rs#L31

2024-11-08 00:39 UTC, alistair23 commented on src/usb_i2c.rs
> +        io_buffers::libspdm_setup_io_buffers(context, SEND_RECEIVE_BUFFER_LEN, LIBSPDM_BUFFER_LEN)?;
Ah ok!

2024-11-08 00:45 UTC, twilfredo commented on src/io_buffers.rs
> +/// Panics if the SEND_BUFFER is not available
fixed!

2024-11-08 00:58 UTC, alistair23 approved these changes

2024-11-08 00:59 UTC, merged