mctp: wip2: add i2c transport
westerndigitalcorporation/spdm-utils pull request #30
Opened 2023-12-13 02:31 UTC by twilfredo

@alistair23 I noticed on this branch the .tab size is ~100K higher than my original, I think because of the new dependencies added to the cargo.toml.

2023-12-13 04:25 UTC, alistair23 requested changes

2023-12-13 04:25 UTC, alistair23 commented on src/libspdm/spdm.rs
> +pub const LIBSPDM_MAX_SPDM_MSG_SIZE: u32 = 0x100;
We don't want to change the main library

2023-12-13 04:25 UTC, alistair23 commented on src/libspdm/spdm.rs
> +        Some(libspdm_transport_mctp_decode_message),
Same here

2023-12-13 04:25 UTC, alistair23 commented on tock-responder/src/main.rs
> +stack_size! {0x800}
0xE00 is what I need for OT

2023-12-13 04:37 UTC, twilfredo commented on src/libspdm/spdm.rs
> +pub const LIBSPDM_MAX_SPDM_MSG_SIZE: u32 = 0x100;
okay, I'll add a modified version to tock-responder?

2023-12-13 04:43 UTC, alistair23 commented on src/libspdm/spdm.rs
> +pub const LIBSPDM_MAX_SPDM_MSG_SIZE: u32 = 0x100;
Yeah. That is probably the way to go

2023-12-13 05:08 UTC, twilfredo commented
Addressed your comments @alistair23 :)

2023-12-14 03:59 UTC, twilfredo commented
@alistair23  do you have a better idea as to what maybe happening here https://github.com/westerndigitalcorporation/spdm-utils/pull/30/commits/9b9e6b0bced2dd11686bc9d3cb22ca5024ff4d76 ?

2023-12-15 03:06 UTC, alistair23 commented
> @alistair23 do you have a better idea as to what maybe happening here [9b9e6b0](https://github.com/westerndigitalcorporation/spdm-utils/commit/9b9e6b0bced2dd11686bc9d3cb22ca5024ff4d76) ?

Strange... I'm not sure. Allocating it on the heap isn't a bad thing though, so we might just keep that commit

2023-12-15 03:16 UTC, alistair23 commented on tock-responder/src/mctp.rs
> +pub const TARGET_ID: u8 = 0x22;
A device should only have a single address, so this sounds ok. We probably want to make this configurable somehow though

2023-12-15 03:16 UTC, alistair23 commented on tock-responder/src/mctp.rs
> +    // TODO: LIBSPDM_MAX_SPDM_MSG_SIZE do we need to reduce this?
I don't think there is a TODO here, this looks fine

2023-12-15 03:16 UTC, alistair23 commented on tock-responder/src/mctp.rs
> +    // TODO: Use the libtock-rs I2C api to send the buffer
Isn't this supported?

2023-12-15 03:16 UTC, alistair23 commented on tock-responder/src/mctp.rs
> +    Alarm::sleep_for(Milliseconds(250)).unwrap();
Why do we need a sleep here?

2023-12-15 03:16 UTC, alistair23 commented on tock-responder/src/mctp.rs
> +    unimplemented!("mctp_send_message");
Is this unimplemented?

2023-12-15 03:16 UTC, alistair23 commented on tock-responder/src/mctp.rs
> +        // TODO: These will never be freed. Perhaps there's a better way to
I think that's ok. They live as long as the application is running

2023-12-18 10:13 UTC, twilfredo commented
@alistair23  this is now functional on nrf52840/particle_boron without depending on `newlib` & `libtock-c`. Let me know if you see any red flags with the libc stub implementation code. They seem to work fine so far...

2023-12-20 00:42 UTC, alistair23 requested changes

2023-12-20 00:42 UTC, alistair23 commented on tock-responder/src/main.rs
> +        Some(u8::try_from(libspdm::libspdm_rs::SPDM_MESSAGE_VERSION_13).unwrap()),
I think this should be split out to it's own commit (with a justification of why we need this)

2023-12-20 00:42 UTC, alistair23 commented on tock-responder/src/mctp.rs
> +// TODO: We can get away with using the same ID for send/recv as the there's only
I think we can remove this TODO

2023-12-20 00:42 UTC, alistair23 commented on tock-responder/src/libc_stubs.rs
> +    let layout: Layout = core::ptr::read(layout_addr as *const Layout).clone();
I don't think we need the `clone()`

2023-12-20 00:42 UTC, alistair23 commented on tock-responder/src/main.rs
> +stack_size! {0x4000}
Is this just because we are replacing the C functions? That's a massive increase!

2023-12-20 00:42 UTC, alistair23 commented on tock-responder/src/main.rs
> +        Some(u8::try_from(libspdm::libspdm_rs::SPDM_MESSAGE_VERSION_12).unwrap()),
Why change this back?

2023-12-20 00:46 UTC, twilfredo commented on tock-responder/src/main.rs
> +stack_size! {0x4000}
No, it seems like we run into stack overflow issues in the later calls in libspdm. I only noticed them here because we hadn't got that far yet. Not related to the C functions as far as I can tell.

2023-12-20 00:48 UTC, twilfredo commented on tock-responder/src/main.rs
> +        Some(u8::try_from(libspdm::libspdm_rs::SPDM_MESSAGE_VERSION_12).unwrap()),
I'm not sure if this is fixed yet, but there were 1.3 compliance issues last time we were testing the linux kernel implementation. So i just wanted to make sure we were working off a more stable base till this is ready, then bump it up.

2023-12-20 00:50 UTC, twilfredo commented on .gitmodules
> +	url = https://github.com/twilfredo/libtock-rs.git
This is the main change we need: https://github.com/twilfredo/libtock-rs/commit/08d32ca3cbebdb8c8b58cf025faf4ae1bc754b6c

Do you think it is upstream-able?

2023-12-20 00:56 UTC, alistair23 commented
I squashed https://github.com/westerndigitalcorporation/spdm-utils/pull/30/commits/d4d5120f8abd88863f350c0c0a229418fc5168d0 into https://github.com/westerndigitalcorporation/spdm-utils/pull/32 so we can get the MCTP part merged

2024-01-04 05:44 UTC, twilfredo commented
Rebased on master. This also depends on https://github.com/westerndigitalcorporation/spdm-utils/pull/34

2024-01-10 01:22 UTC, alistair23 requested changes

2024-01-10 01:22 UTC, alistair23 commented on .gitmodules
> +	url = https://github.com/twilfredo/libtock-rs.git
We should be able to switch back to upstream here

2024-01-10 01:22 UTC, alistair23 commented on tock-responder/src/libc_stubs.rs
> +}
Throw a TODO in here?

2024-01-10 23:33 UTC, alistair23 requested changes

2024-01-10 23:33 UTC, alistair23 commented on tock-responder/src/main.rs
> -}
We still need this for RISC-V

2024-01-10 23:33 UTC, alistair23 commented on tock-responder/src/libc_stubs.rs
> +//! Implementation of the libc functions required by libspdm
Can you try `make opentitan_spdm_responder` as well? I get some missing function errors

2024-01-11 01:29 UTC, twilfredo commented on tock-responder/src/libc_stubs.rs
> +//! Implementation of the libc functions required by libspdm
yep, took awhile to compile the riscv toolchain. I have opentitan compiling with the addition of the new stubs in the latest commit

2024-01-11 01:35 UTC, twilfredo commented on tock-responder/src/libc_stubs.rs
> +//! Implementation of the libc functions required by libspdm
Also note, I'm building libspdm in **release** mode, otherwise debug requires printf.

2024-01-11 02:27 UTC, alistair23 commented on tock-responder/README.md
> +cmake -DARCH=riscv32 -DTOOLCHAIN=RISCV_NONE -DTARGET=Debug -DCRYPTO=mbedtls -DDISABLE_TESTS=1 CFLAGS="-DLIBSPDM_ENABLE_CAPABILITY_CHUNK_CAP=1" ..
Doesn't this need to be `Release` mode?

We should also throw in a big warning saying debug mode doesn't work

2024-01-11 02:42 UTC, twilfredo commented on tock-responder/src/libc_stubs.rs
> +}
fixed with: https://github.com/westerndigitalcorporation/spdm-utils/pull/30/commits/bce2e7bd515f0348d0b2a660047f0265e8f24cce

2024-01-11 02:42 UTC, twilfredo commented on tock-responder/src/libc_stubs.rs
> +}
I'll fold the patches when we are ready to merge

2024-01-11 02:43 UTC, twilfredo commented on tock-responder/README.md
> +cmake -DARCH=riscv32 -DTOOLCHAIN=RISCV_NONE -DTARGET=Debug -DCRYPTO=mbedtls -DDISABLE_TESTS=1 CFLAGS="-DLIBSPDM_ENABLE_CAPABILITY_CHUNK_CAP=1" ..
yeah this should be `debug`, okay I'll add a warning

2024-01-11 02:50 UTC, alistair23 commented on tock-responder/src/libc_stubs.rs
> +//! Implementation of the libc functions required by libspdm
That's a pain! For now that'll have to do though

2024-01-11 03:20 UTC, alistair23 approved these changes

2024-01-11 03:56 UTC, merged