spdm-utils: transport: usb-i2c support
westerndigitalcorporation/spdm-utils pull request #33
Opened 2023-12-20 03:10 UTC by twilfredo

This adds a supporting transport layer, designed to work with the libtock-rs usb-i2c bridge app.

2023-12-20 03:51 UTC, twilfredo commented
update: rebased on maser now

2024-01-10 01:15 UTC, alistair23 requested changes

2024-01-10 01:15 UTC, alistair23 commented on Cargo.toml
> +lazy_static = "1.4.0"
This breaks `tock-responder` building, you need something like this instead

```
serialport = { version = "4.3.0", optional = true }
lazy_static = { version = "1.4.0", optional = true }
```

2024-01-10 01:15 UTC, alistair23 commented on README.md
> +cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=openssl -DENABLE_BINARY_BUILD=1 -DCOMPILED_LIBCRYPTO_PATH=/usr/lib/ -DCOMPILED_LIBSSL_PATH=/usr/lib/ -DDISABLE_TESTS=1 CFLAGS="-DLIBSPDM_ENABL
Should we just use this by default?

2024-01-10 23:35 UTC, twilfredo commented on README.md
> +cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=openssl -DENABLE_BINARY_BUILD=1 -DCOMPILED_LIBCRYPTO_PATH=/usr/lib/ -DCOMPILED_LIBSSL_PATH=/usr/lib/ -DDISABLE_TESTS=1 CFLAGS="-DLIBSPDM_ENABL
Yeah I think we could, is it worth leaving this to specify that u2c-i2c requires chunking?

2024-01-10 23:54 UTC, alistair23 commented on README.md
> +cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=openssl -DENABLE_BINARY_BUILD=1 -DCOMPILED_LIBCRYPTO_PATH=/usr/lib/ -DCOMPILED_LIBSSL_PATH=/usr/lib/ -DDISABLE_TESTS=1 CFLAGS="-DLIBSPDM_ENABL
It's probably worth saying that `usb_i2c` requires chunking, but then just enable it in our default build. That way we can simplify things for users (one build and done)

2024-01-11 04:36 UTC, twilfredo commented on Cargo.toml
> +lazy_static = "1.4.0"
good catch, thanks!

2024-01-11 04:37 UTC, twilfredo commented
Addressed the changes above

2024-01-11 06:22 UTC, alistair23 commented on README.md
> +if the target endpoint device requires it. Chunking allows us to keep the maximum data transferred in a single burst down by chunking the spdm message data into frames of digestible size(s).
I think this need a proof read. Maybe

```
Chunking allows us to keep the maximum data transferred in a single burst down by chunking the SPDM message data into frames of digestible size(s).

`usb_i2c` communication with the tock-responder requires it, so we enable it by default. You can disable `LIBSPDM_ENABLE_CAPABILITY_CHUNK_CAP` for other targets if required.
```

2024-01-11 06:25 UTC, alistair23 requested changes

2024-01-11 06:25 UTC, alistair23 commented on src/usb_i2c.rs
> +        }
This is a bit odd. I suspect it's somehow related to how the nRF is flashed, but it seems very brittle. Does a board reset fix this?

Or, we could read all of the UART in the setup function to "clear" the buffers before we start

2024-01-11 06:45 UTC, twilfredo commented on src/usb_i2c.rs
> +        }
Yeah it works with a with a board reset. From memory, this happens on the first try immediately after flashing.

We do clear the rx/tx buffers `register_device()` on the host side. I suspect it's something in the tock kernel buffers, for whatever reason it appends the message (from tock-userspace) two offsets into the kernel TX buffer (or so it seems...). I didn't look too closely into it, but I did try reading the UART from the host and it was empty up until the device issued a write. This write contains the data message with that odd offset.

2024-01-12 02:42 UTC, alistair23 commented on src/usb_i2c.rs
> +        }
I feel like we shouldn't have this. I suspect it's hiding a bug and seems really brittle

2024-01-12 02:43 UTC, twilfredo commented on src/usb_i2c.rs
> +        }
yeah it is a hacky fix for a minor inconvenience. I'll drop it.

2024-01-12 03:57 UTC, twilfredo commented on src/usb_i2c.rs
> +        }
dropped in https://github.com/westerndigitalcorporation/spdm-utils/pull/33/commits/0d6df8d05fd2dfd7b067fc8ccdd121a7238e924a

made a separate commit incase it's helpful when debugging later on (we can just revert).

2024-01-12 03:58 UTC, alistair23 commented on src/usb_i2c.rs
> +// Copyright (C) 2022, Western Digital Corporation or its affiliates.
2024

2024-01-12 04:00 UTC, alistair23 commented
Looks good, just the README comment then it's good to go

2024-01-12 04:00 UTC, twilfredo commented on src/usb_i2c.rs
> +// Copyright (C) 2022, Western Digital Corporation or its affiliates.
fixed

2024-01-12 04:05 UTC, twilfredo commented
> Looks good, just the README comment then it's good to go

updated :)

2024-01-12 05:31 UTC, alistair23 approved these changes

2024-01-12 05:35 UTC, merged