Support the full MCTP protocol
westerndigitalcorporation/spdm-utils pull request #38
Opened 2024-01-19 02:22 UTC by alistair23

2024-01-19 02:25 UTC, twilfredo commented
Nice, did you have a go at testing this?

2024-01-19 02:28 UTC, alistair23 commented
It runs for me, but eventually I get an error sending the data. I *think* that's an I2C issue and not related to this change

2024-01-19 02:31 UTC, twilfredo commented
> It runs for me, but eventually I get an error sending the data. I _think_ that's an I2C issue and not related to this change

Okay, I'll run some tests soon... then merge if all good. 

Should we add  some scripted unit tests for hardware testing, basically something to invoke spdm-utils and do assertions on the outputs?

2024-01-19 02:33 UTC, alistair23 commented
> Should we add some scripted unit tests for hardware testing, basically something to invoke spdm-utils and do assertions on the outputs?

Yeah, that would be handy!

2024-01-21 23:25 UTC, twilfredo requested changes

2024-01-21 23:25 UTC, twilfredo commented on src/usb_i2c.rs
> +    let (_msg_type, payload) = ctx.decode_packet(&spdm_msg_buf[0..mctp_len]).unwrap();
Running into a panic in `libmctp` when I issue a request from `spdm-utils`

```
                          Particle Boron: Initialization complete. Entering main loop
spdm-sample: app start
spdm-sample: setup_transport_layer [ok]
spdm-sample: setup_capabilities [ok]
spdm-sample: starting response_loop...
panicked at 'range end index 8 out of range for slice of length 6', /home/twilfred/.cargo/git/checkouts/libmctp-e88d4618e42006d6/f9b4473/src/smbus.rs:224:42
```

It's called by the call to `decode_packet` in the case where the slice passed in is has < 8 indexes. Call path in libmctp -> decode_packet() -> get_smbus_headers(), then panic: `base_header_buf.copy_from_slice(&packet[4..8]);`

2024-01-21 23:42 UTC, twilfredo requested changes

2024-01-21 23:42 UTC, twilfredo commented on tock-responder/src/mctp.rs
> +    let (_msg_type, payload) = ctx.decode_packet(&recv_buf[0..message_len]).unwrap();
Running into a panic in `libmctp` when I issue a request from `spdm-utils`

```
                          Particle Boron: Initialization complete. Entering main loop
spdm-sample: app start
spdm-sample: setup_transport_layer [ok]
spdm-sample: setup_capabilities [ok]
spdm-sample: starting response_loop...
panicked at 'range end index 8 out of range for slice of length 6', /home/twilfred/.cargo/git/checkouts/libmctp-e88d4618e42006d6/f9b4473/src/smbus.rs:224:42
```

It's called by the call to `decode_packet` in the case where the slice passed in has < 8 indexes (`&recv_buf[0..message_len]`). Call path in libmctp -> decode_packet() -> get_smbus_headers(), then panic `L224:smbus.rs`: `base_header_buf.copy_from_slice(&packet[4..8]);`

2024-01-21 23:45 UTC, twilfredo commented on tock-responder/src/mctp.rs
> +    let (_msg_type, payload) = ctx.decode_packet(&recv_buf[0..message_len]).unwrap();
Updated: with `spdm-debug` mode outputs

2024-01-22 01:13 UTC, alistair23 commented on tock-responder/src/mctp.rs
> +    let (_msg_type, payload) = ctx.decode_packet(&recv_buf[0..message_len]).unwrap();
`[44, 5, 10, 84, 0, 0]` isn't a valid MCTP packet, it looks like just a plain SPDM payload. Something odd is going on here

2024-01-22 03:29 UTC, twilfredo commented on src/usb_i2c.rs
> +    assert!(mctp_len <= message_len);
this assertion fails, how do we know what `spdm_msg_buf[2]` is?

2024-01-22 03:31 UTC, twilfredo commented on src/usb_i2c.rs
> +    spdm_msg_buf.copy_within(9..(9 + len), 1);
what is happening here? this is hard to follow?

2024-01-22 03:33 UTC, twilfredo commented on tock-responder/src/mctp.rs
> +    recv_buf.copy_within(9..(9 + len), 1);
might be better make these into consts so we know what the offsets are doing (same as above).

2024-01-22 03:34 UTC, twilfredo commented on tock-responder/src/mctp.rs
> +    let (_msg_type, payload) = ctx.decode_packet(&recv_buf[0..message_len]).unwrap();
my bad, I forgot to rebuild `spdm-utils` :P

2024-01-22 03:48 UTC, twilfredo commented on tock-responder/src/mctp.rs
> +    recv_buf.copy_within(9..(9 + len), 1);
or some comments

2024-01-22 23:29 UTC, alistair23 commented on src/usb_i2c.rs
> +    assert!(mctp_len <= message_len);
It's the byte count of an MCTP packet. What values are you seeing in the failure?

2024-01-22 23:32 UTC, twilfredo commented on src/usb_i2c.rs
> +    assert!(mctp_len <= message_len);
I put a debug to print out the two values:
```
[2024-01-22T23:32:18Z DEBUG spdm_utils::usb_i2c] mctp_len: 18  message_len: 16
thread 'main' panicked at 'assertion failed: mctp_len <= message_len', src/usb_i2c.rs:200:5
```

2024-02-06 06:14 UTC, twilfredo approved these changes

2024-02-06 06:14 UTC, merged