spdm: add manifest cbor enc/dec support
westerndigitalcorporation/spdm-utils pull request #45
Opened 2024-02-21 04:32 UTC by twilfredo

## Overview

This adds support to spdm-utils to be able to cbor serialise a `manifest.in.cbor` file at compile time, then use the output binary file created as the `measurement manifest` to be used during a `get-measurements` index `0xFD` request.

The requester is also now able to decode this received manifest and print it out to the user in a human readable format.

2024-02-21 04:59 UTC, alistair23 commented on README.md
> +spdm-utils required [cbor2](https://pypi.org/project/cbor2/) python module for manifest encoding and decoding. It can be installed with:
requires

2024-02-21 05:14 UTC, alistair23 requested changes

2024-02-21 05:14 UTC, alistair23 commented on build.rs
> +    let rc = Command::new("python3")
Maybe add a comment here saying that this generates `manifest.out.cbor`. That way someone can grep how the file is generated

2024-02-21 05:14 UTC, alistair23 commented on src/libspdm/manifest.rs
> +        }
Can you use copy_from_slice?

https://doc.rust-lang.org/std/vec/struct.Vec.html#method.as_slice

2024-02-21 05:14 UTC, alistair23 commented on src/libspdm/manifest.rs
> +        }
Actually, you can just use [`read()`](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) directory and not have the vector

2024-02-21 05:14 UTC, alistair23 commented on src/libspdm/spdm.rs
> +                    &measurement_record[7..measurement_record_length as usize];
Can we macro `7`?

2024-02-21 06:18 UTC, twilfredo commented on README.md
> +spdm-utils required [cbor2](https://pypi.org/project/cbor2/) python module for manifest encoding and decoding. It can be installed with:
what do you mean by "the/g"?

2024-02-21 22:19 UTC, twilfredo commented on README.md
> +spdm-utils required [cbor2](https://pypi.org/project/cbor2/) python module for manifest encoding and decoding. It can be installed with:
addressed all the comments except for the "the/g" ^ still not sure :P

2024-02-22 00:44 UTC, alistair23 commented on README.md
> +spdm-utils required [cbor2](https://pypi.org/project/cbor2/) python module for manifest encoding and decoding. It can be installed with:
Replace `required` with `requires the`

2024-02-22 00:46 UTC, twilfredo commented on README.md
> +spdm-utils required [cbor2](https://pypi.org/project/cbor2/) python module for manifest encoding and decoding. It can be installed with:
ah! fixed

2024-02-22 01:20 UTC, alistair23 approved these changes

2024-02-22 01:22 UTC, merged