requester: add cli support for fetching a raw-bitstream + tests
westerndigitalcorporation/spdm-utils pull request #70
Opened 2024-05-13 02:54 UTC by twilfredo

2024-05-14 01:34 UTC, alistair23 requested changes

2024-05-14 01:34 UTC, alistair23 commented on src/libspdm/manifest.rs
> +                    false,
I think we want this to be true

2024-05-14 01:34 UTC, alistair23 commented on src/test_suite.rs
> +                            true
Why not just request raw for all of them?

2024-05-14 01:34 UTC, alistair23 commented on src/test_suite.rs
> +                }
It's possible that we request a raw bit stream but don't get one as the device doesn't support it. We should check and report that

2024-05-14 01:41 UTC, twilfredo commented on src/test_suite.rs
> +                            true
So test getting all of the measurements of both types from the device.

2024-05-14 02:06 UTC, twilfredo commented on src/libspdm/manifest.rs
> +                    false,
good point, I'm noticing that the responder doesn't like to share the raw-bitstream for index 1/2 (we have so far been getting just the hash). 

How should we handle this?

2024-05-14 03:11 UTC, alistair23 commented on src/libspdm/manifest.rs
> +                    false,
It's valid for a responder to not return the raw bit stream. pg 106 of SPDM 1.3 says:

> If the Responder cannot return a raw bit stream for the measurement (for example, if the raw bit stream contains confidential data that the Responder cannot expose), it shall return the corresponding hash.

So we shouldn't get an error, we should just get a digest. libspdm might see that as an error though, we need to check that

2024-05-14 03:12 UTC, alistair23 commented on src/libspdm/manifest.rs
> +                    false,
As for handling it. We should ask for the raw bit stream and then insert whatever is returned. If the responder only gives us a digest then that's what we use

2024-05-14 03:14 UTC, twilfredo commented on src/libspdm/manifest.rs
> +                    false,
Been digging more into this, it's failing "https://github.com/DMTF/libspdm/blob/999ed70ee185c065ae09fed7b85c69a19179fcf1/library/spdm_requester_lib/libspdm_req_get_measurements.c#L640" as far as I can tell the responder message status is OK. The logic here is a bit confusing

2024-05-14 03:14 UTC, alistair23 commented on src/test_suite.rs
> +                            true
It's valid to request a digest of the manifest as well though. So checking for `SPDM_MEASUREMENT_BLOCK_MEASUREMENT_INDEX_MEASUREMENT_MANIFEST` doesn't seem like the right approach.

We should either just ask for one type or both, not a mix and match

2024-05-14 03:20 UTC, twilfredo commented on src/test_suite.rs
> +                            true
yeah, but a manifest in digest form is not useful in the context of `do_tcg_dice_evidence_binding_request_checks()`, since it isn't parse-able? So we keep that unchanged and test  `both` case in `request_all_measurements()`.

Basically, I just kept the functionality of `do_tcg_dice_evidence_binding_request_checks()` unchanged and added a separate test to request both raw/hash measurement forms.

2024-05-14 03:47 UTC, twilfredo commented on src/libspdm/manifest.rs
> +                    false,
okay so there was bug in our responder, fixed with https://github.com/westerndigitalcorporation/spdm-utils/pull/70/commits/3d9c2c26881eb7f8af70dfa901fb4feee2bbc6f4

2024-05-14 04:04 UTC, twilfredo commented on src/test_suite.rs
> +                            true
Nevermind, I've changed it just request `rawbitstream`, I misunderstood what it's doing. I think what you said makes more sense.

2024-05-14 04:19 UTC, alistair23 commented on src/test_suite.rs
> +                }
We should still report if we don't get the type we expected

2024-05-14 07:53 UTC, twilfredo commented on src/test_suite.rs
> +                    }
@alistair23 added this to inform us if we didn't get the raw-bitsream when requested, so responder returned only a hash. Tested with changing the responder measurement side to omit raw-bitstream flag (it did not trigger any libspdm errors).

2024-05-14 08:05 UTC, twilfredo commented on src/test_suite.rs
> +                    }
@alistair23 added this to inform us if we didn't get the raw-bitsream when requested, so responder returned only a hash. Tested with changing the responder measurement side to omit raw-bitstream flag (it **did not** trigger any libspdm return errors,).

2024-05-14 23:08 UTC, alistair23 commented on src/test_suite.rs
> +                    }
Awesome! A responder is also allowed to do the opposite (not return a digest when asked) so we should flag that as well

2024-05-14 23:20 UTC, twilfredo commented on src/test_suite.rs
> +                    }
Ah okay, I thought that would be an error case... will fix!

2024-05-15 00:33 UTC, twilfredo commented on src/test_suite.rs
> +                    }
Fixed!

2024-05-15 01:10 UTC, alistair23 approved these changes

2024-05-15 01:10 UTC, merged