Add dynamic image measurement
westerndigitalcorporation/spdm-utils pull request #95
Opened 2024-07-30 06:28 UTC by alistair23

Add a command line argument for responders to enable dynamic image measurement. This allows us to more accuratly model a real respnoder.

At startup we spawn two threads to hash the "kernel" and the application. We currently join them before running the responder, we actually only need to do this before generating the measurement, but there isn't a nice way to do that from the libspdm Rust library. I thought of a closure callback, but it's all a bit messy so the current approach will do for now.

`libspdm_fill_measurement_image_hash_block()` will now dynamically use a type of image block based on the init status of the `Lazy` `DYN_IMAGE_MEASURE`.

2024-07-30 06:31 UTC, alistair23 commented
I feel like this is overlay complicated, but it's hard to integrate it with the C libspdm callbacks and the Rust libspdm crate

2024-07-30 06:39 UTC, alistair23 commented
https://github.com/westerndigitalcorporation/spdm-utils/pull/96 should be merged first to fix the CI first

2024-07-30 06:52 UTC, twilfredo approved these changes
looks good! left some suggestions

2024-07-30 06:52 UTC, twilfredo commented on src/libspdm/spdm.rs
> +/// Use the already calculate `DYN_IMAGE_MEASURE` to fill the image
s/calculate/calculated

2024-07-30 06:52 UTC, twilfredo commented on src/libspdm/spdm.rs
> +            let dyn_image_measure = &DYN_IMAGE_MEASURE.read().unwrap();
this function assumes that DYN_IMAGE_MEASURE is ready. If it's exclusively the responsibility of the caller to check, might be worth documenting or just add a check and return an error.

2024-07-30 06:52 UTC, twilfredo commented on src/main.rs
> +                join_all(t).await;
We could check the task return status and make them return errors on failures. Currently it looks like both of these functions prefer to `panic` on `unwrap` failures.... thoughts?

2024-07-30 06:52 UTC, twilfredo commented on src/libspdm/spdm.rs
> +    /// at start up and then access via the
s/access/accessed

2024-07-30 06:52 UTC, twilfredo commented on src/libspdm/spdm.rs
> +    /// at start up and then access via the
s/access/accessed

2024-07-30 06:52 UTC, twilfredo commented on src/libspdm/spdm.rs
> +fn libspdm_fill_measurement_image_hash_block(
does the header comment need to be updated here?

2024-07-30 23:21 UTC, alistair23 commented on src/libspdm/spdm.rs
> +fn libspdm_fill_measurement_image_hash_block(
I don't think so

2024-07-30 23:30 UTC, alistair23 commented on src/libspdm/spdm.rs
> +            let dyn_image_measure = &DYN_IMAGE_MEASURE.read().unwrap();
Good idea, added a check

2024-07-30 23:30 UTC, alistair23 commented on src/libspdm/spdm.rs
> +fn libspdm_fill_measurement_image_hash_block(
But I did anyway :)

2024-07-31 00:13 UTC, twilfredo requested changes
looks good, left some comments

2024-07-31 00:13 UTC, twilfredo commented on src/libspdm/spdm.rs
> +            let populated = Lazy::force(dyn_image_measure).kernel_hashes_populated;
s/kernel_hashes_populated/app_hashes_populated

2024-07-31 00:13 UTC, twilfredo commented on src/libspdm/spdm.rs
> +    /// Have the kernel hashes been populated
s/kernel/app

2024-07-31 00:13 UTC, twilfredo commented on src/libspdm/spdm.rs
> +            }
also I think you could (below), and remove the `populated`, here and above. Either works though :)
```
if !Lazy::force(dyn_image_measure).kernel_hashes_populated { error!("Responder App hashes not generated"); return 0; }
```

2024-07-31 00:13 UTC, twilfredo commented on src/main.rs
> +                }
nice!

2024-07-31 00:39 UTC, alistair23 commented on src/main.rs
> +                join_all(t).await;
Yeah. Good point.

2024-07-31 00:43 UTC, twilfredo approved these changes

2024-07-31 00:50 UTC, merged