Add support for sending explicit SPDM requests.
westerndigitalcorporation/spdm-utils pull request #97
Opened 2024-08-01 07:06 UTC by twilfredo

Currently,  `spdm-utils`  will initialise a connection and sending the user specified SPDM request (`requst <CMD>`). However, this may not be desired, if a user intends to send only the specified command. This could particularly be useful for debugging/development/testing & CI.

This patch adds supports to a new command `requests-only` which will issue only the commands listed. See README for usage.

2024-08-02 05:33 UTC, alistair23 requested changes

2024-08-02 05:33 UTC, alistair23 commented on src/main.rs
> +        requests: std::vec::Vec<RequestCode>,
I think we should support a list with the existing `request` command and then just add an argument to skip the init. Otherwise we have to duplicate the request arguments

2024-08-02 05:33 UTC, alistair23 commented on src/main.rs
> +        /// NO_MEASUREMENT_SUMMARY_HASH,ft yet implemented
?

2024-08-02 05:33 UTC, alistair23 commented on src/main.rs
> +    init_logger();
Why switch this order?

2024-08-02 05:33 UTC, alistair23 commented on src/request.rs
I don't follow

2024-08-02 06:54 UTC, twilfredo commented on src/main.rs
> +    init_logger();
There's a debug that comes out before args are parsed otherwise... which looks really odd.

2024-08-02 06:54 UTC, twilfredo commented on src/main.rs
> +        /// NO_MEASUREMENT_SUMMARY_HASH,ft yet implemented
typo, will fix up

2024-08-02 06:55 UTC, twilfredo commented on src/main.rs
> +        requests: std::vec::Vec<RequestCode>,
yeah good point

2024-08-02 06:59 UTC, twilfredo commented on src/request.rs
yeah just realized this looks silly. Basically in https://github.com/westerndigitalcorporation/spdm-utils/pull/97/commits/44cdbe72a7f910685eb0eb39383b79dfc966a106 we make sure we actually send the GET_VERSION and GET_CAPABILITIES requests instead of just extracting established data from the session context.

It seems like `GET_CAPABILITIES` is only allowed to be issued once per `GET_VERSION`. So it is issued during `initialise_connection` and also if it is selected as a request by the user. The latter of which will cause an error. So make sure we handle it gracefully.

2024-08-02 06:59 UTC, twilfredo commented on src/request.rs
This was picked up by the CI actually, and is addressed in https://github.com/westerndigitalcorporation/spdm-utils/pull/97/commits/0e27d3378fd1161be5b6fb87022520015bccad55

2024-08-02 07:00 UTC, twilfredo commented on src/main.rs
> +    init_logger();
For context, if the args failed to parse, we don't want  debug message saying logger was initialized prior to the arg parse failure msg.

2024-08-02 07:29 UTC, alistair23 commented on src/main.rs
> +    init_logger();
Makes sense. But what if we want to log in the arg parser?

2024-08-02 07:30 UTC, alistair23 commented on src/request.rs
Ah cool! Maybe split the commits up into separate PRs?

2024-08-04 23:51 UTC, twilfredo commented on src/main.rs
> +    init_logger();
Hmm, I suppose we could do logging from a custom parser function which would get invoked through `parse()`. I'll drop this change then.

2024-08-05 00:19 UTC, twilfredo commented on src/main.rs
> +        requests: std::vec::Vec<RequestCode>,
I'm trying to think of a good way to do this, it becomes a bit tricky because some of the requestCodes have sub arguments. So if requests were specified in a list, would something like this be ok?

`requestA{subargs}, requestB, requestC, requestD{subargs}`

2024-08-05 04:54 UTC, alistair23 commented on src/main.rs
> +        requests: std::vec::Vec<RequestCode>,
Hmm... Good point

That seems ok to me, I don't have any better ideas

2024-08-07 04:17 UTC, twilfredo commented
continued in #101

2024-08-07 04:17 UTC, closed without merging